# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
  job:
    chdir: True
  run:
    dir: ./inverse_fno_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

start_lr: 0.001
gamma: 0.99948708
max_epochs: 200

batch_size: 32
validation_batch_size: 1

data:
  train_path: ./datasets/Darcy_241/piececonst_r241_N1024_smooth1.hdf5
  validation_path: ./datasets/Darcy_241/piececonst_r241_N1024_smooth2.hdf5
  resolution: 240

scaling:
  permeability: 4.49996e00
  darcy: 3.88433e-03

physics_weight: 1.0
physics_residual_normalizer: 240.0
physics_balance_eps: 1.0e-8
physics_forcing_term: 1.0

model:
  fno:
    in_channels: 1
    out_channels: 1
    decoder_layers: 1
    decoder_layer_size: 32
    dimension: 2
    latent_channels: 48
    num_fno_layers: 5
    num_fno_modes: 16
    padding: 9